import { GoogleGenAI, Type, Schema } from '@google/genai';
import dotenv from 'dotenv';
import { buildSystemInstruction } from './prompts';

dotenv.config();

// The SDK automatically picks up GEMINI_API_KEY from process.env
const ai = new GoogleGenAI({});

// LRU-style in-memory cache to prevent duplicate expensive LLM calls
const responseCache = new Map<string, NegotiationResult>();

export enum DetectedSentiment {
  ANGRY = 'angry',
  NEUTRAL = 'neutral',
  HAPPY = 'happy',
  PANICKED = 'panicked',
  CURIOUS = 'curious'
}

export enum NegotiationStatus {
  IN_PROGRESS = 'in_progress',
  ACCEPTED = 'accepted',
  REJECTED = 'rejected',
  INFORMATIONAL = 'informational'
}

/**
 * Represents the structured JSON response generated by the Gemini AI.
 */
export interface NegotiationResult {
  spoken_response: string;
  detected_sentiment: DetectedSentiment;
  negotiation_status: NegotiationStatus;
  awarded_perk: string | null;
}

/**
 * Communicates with the Gemini 2.5 Flash model to negotiate with fans or assist volunteers.
 * 
 * @param transcript The user's spoken input or text query.
 * @param budget The max budget allocated for this specific zone/fan.
 * @param availablePerks List of perks that can be offered (e.g., "Free Drink", "VIP Access").
 * @param language The language the user spoke in, and the expected language for the AI response.
 * @param role The role of the user (e.g., "fan", "volunteer").
 * @returns A parsed NegotiationResult containing the AI's response and state changes.
 */
export const negotiateWithFan = async (
  transcript: string, 
  budget: number, 
  availablePerks: string[],
  language: string = 'English',
  role: string = 'fan'
): Promise<NegotiationResult> => {
  
  const systemInstruction = buildSystemInstruction(role, language, budget, availablePerks);

  const responseSchema: Schema = {
    type: Type.OBJECT,
    properties: {
      spoken_response: {
        type: Type.STRING,
        description: `What Aura will say back to the user verbally, strictly in ${language}.`
      },
      detected_sentiment: {
        type: Type.STRING,
        enum: ['angry', 'neutral', 'happy', 'panicked', 'curious'],
        description: "The emotional state of the user."
      },
      negotiation_status: {
        type: Type.STRING,
        enum: ['in_progress', 'accepted', 'rejected', 'informational'],
        description: "Status of the interaction."
      },
      awarded_perk: {
        type: Type.STRING,
        nullable: true,
        description: "If accepted, the exact name of the perk given. Otherwise null."
      }
    },
    required: ["spoken_response", "detected_sentiment", "negotiation_status"]
  };

  // Phase 2: Performance - Cache AI responses where safe
  const cacheKey = `${language}:${role}:${transcript.toLowerCase().trim()}`;
  if (responseCache.has(cacheKey)) {
    return responseCache.get(cacheKey)!;
  }

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: transcript,
      config: {
        systemInstruction,
        responseMimeType: "application/json",
        responseSchema: responseSchema,
        temperature: 0.4
      }
    });

    if (!response.text) {
      throw new Error("No response generated from Gemini");
    }
    
    const result = JSON.parse(response.text) as NegotiationResult;
    
    // Store in cache to optimize future repeated identical queries (e.g. "where is the bathroom")
    if (responseCache.size > 1000) responseCache.clear(); // Basic eviction
    responseCache.set(cacheKey, result);
    
    return result;
    
  } catch (error) {
    console.error("Gemini AI Error:", error);
    return {
      spoken_response: "I'm having trouble connecting right now, but please stay safe.",
      detected_sentiment: DetectedSentiment.NEUTRAL,
      negotiation_status: NegotiationStatus.IN_PROGRESS,
      awarded_perk: null
    };
  }
};
